# version: '3.8'

services:

  redis:
    image: redis:6.2
    container_name: redis-stream
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - restaurant-network

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    # restart: always
    environment:
      # - MYSQL_ROOT_PASSWORD=123
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - restaurant-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  base-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: base-backend-image:latest

  order-payment-service:
    build:
      context: ./backend-fastapi/order-payment-service
    container_name: namespace-order-payment-service
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_SERVER=mysql:3333
      - DB_NAME=order_payment_service_db
    ports:
      - "8001:8001"
    volumes:
      - ./backend-fastapi/order-payment-service:/app
    depends_on:
      - mysql
      - base-backend
    networks:
      - restaurant-network

volumes:
  redis_data:
  mysql_data:

networks:
  restaurant-network:
    driver: bridge
